services:
  

  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:2661@db:3306/db_name
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 2661
      MYSQL_DATABASE: db_name
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  frontend:
    build: 
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge
